const words = [
    'あーおなかすいたせかいさいこうみんぞく',
    'みるびーじーえむ',
    'やあちくしょうども、はじめましょう',
    'ぜんぜんはずかしくないです',
    'かいわしたりすぱむしたりするさーばーです',
    'もはやくりぼうさばぜろのめいげんしゅう',
    'くりぼうはするびべ',
    'しんがたういるす',
    'のにさばのすらむがいばーじょん',
    'めんでれーえふ',    //10
    'いいいみでもわるいいみでも',
    'おれをさいようしたきゅーぶはせいかいだった',
    'かはんしんないからしんちょうむげん',
    'どうもうなもうどうけんです',
    'そんなこまんどないよ。ばーか',
    'なにくさはえちらかしてるんだ、やくぞ',
    'ちしきはどくせんするものではなく、きょうゆうするものです',
    'さんぎょうはいきぶつとつがるはんとうのたべすぎ',
    'じんるいなめんな',
    'なおそのぷりんはくりぼうのくちのなかでばくはつした',//20
    'ぼっとぼっとくるぼっと',
    'なんでわからないの',
    'あれ、しゃべたろう？',
    'あ、ちくちくことばだ、たひね',
    'これはめいげん',
    'でぃすいずぼっとましーん、ちーん',
    'ぼっちたからせん',
    'ばーかばーかばーかばーかばーかばーかばーか',
    'このよのものは、たいていめにいれるといたい',
    'くりぼうをさくじょしました', //30
    'ふっかつするなふっかつするなふっかつするな',
    'めんしょん２どめですね、はい。',
    'さいこうにすきなやつひとつといわれたのでふたつめだします',
    'でんしゃなういんぐ',
    'ここ画像映像とーくですけど',
    'みなかったことにしてくれ'
]
const imgs = [
    "curibouimg/0001.png",
    "curibouimg/0002.png",
    "curibouimg/0003.png",
    "curibouimg/0004.png",
    "curibouimg/0005.png",
    "curibouimg/0006.png",
    "curibouimg/0007.png",
    "curibouimg/0008.png",
    "curibouimg/0009.png",
    "curibouimg/0010.png",
    "curibouimg/0011.png",
    "curibouimg/0012.png",
    "curibouimg/0013.png",
    "curibouimg/0014.png",
    "curibouimg/0015.png",
    "curibouimg/0016.png",
    "curibouimg/0017.png",
    "curibouimg/0018.png",
    "curibouimg/0019.png",
    "curibouimg/0020.png",
    "curibouimg/0021.png",
    "curibouimg/0022.png",
    "curibouimg/0023.png",
    "curibouimg/0024.png",
    "curibouimg/0025.png",
    "curibouimg/0026.png",
    "curibouimg/0027.png",
    "curibouimg/0028.png",
    "curibouimg/0029.png",
    "curibouimg/0030.png",
    "curibouimg/0031.png",
    "curibouimg/0032.png",
    "curibouimg/0033.png",
    "curibouimg/0034.png",
    "curibouimg/0035.png",
    "curibouimg/0036.png",
    // "curibouimg/0037.png",
    // "curibouimg/0038.png",
    // "curibouimg/0039.png",
    // "curibouimg/0040.png",
    // "curibouimg/0041.png",
    // "curibouimg/0042.png",
    // "curibouimg/0043.png",
    // "curibouimg/0044.png",
    // "curibouimg/0045.png",
    // "curibouimg/0046.png",
    // "curibouimg/0047.png",
    // "curibouimg/0048.png",
    // "curibouimg/0049.png",
    // "curibouimg/0050.png",
    // "curibouimg/0051.png",
    // "curibouimg/0052.png",
    // "curibouimg/0053.png",
    // "curibouimg/0054.png",
    // "curibouimg/0055.png",
    // "curibouimg/0056.png",
    // "curibouimg/0057.png",
    // "curibouimg/0058.png",
    // "curibouimg/0059.png",
    // "curibouimg/0060.png",
    // "curibouimg/0061.png",
    // "curibouimg/0062.png",
    // "curibouimg/0063.png",
    // "curibouimg/0064.png",
    // "curibouimg/0065.png",
    // "curibouimg/0066.png",
    // "curibouimg/0067.png",
    // "curibouimg/0068.png",
    // "curibouimg/0069.png",
    // "curibouimg/0070.png",
    // "curibouimg/0071.png",
    // "curibouimg/0072.png",
    // "curibouimg/0073.png",
    // "curibouimg/0074.png",
    // "curibouimg/0075.png",
    // "curibouimg/0076.png",
    // "curibouimg/0077.png",
    // "curibouimg/0078.png",
    // "curibouimg/0079.png",
    // "curibouimg/0080.png",
]